#Indentation is super important
version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
      ##Links to other containers
  mongo:
    container_name: mongo
    image: mongo
    #You put image when you have to get it
    ports:
      - '27017:27017'
